### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by soulwire** [bitinn/svgshelf#1]
Hi,

Thanks for the library, looks like it will be very useful since I'm also not using a task runner like gulp and just want to create an svg store from the cli.

I'm having trouble running the `svgshelf` command though - node doesn't seem to like the asterisk:

```
Shelf.prototype.run = function *() {
                               ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/svgshelf/index.js:12:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by bitinn** [comment]
@soulwire oh that's because your node.js doesn't support generator yet, even node.js v0.12 still require `--harmony` flag to enable that feature, see this:

http://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12

So you probably need to `node --harmony svgshelf` (untested, I am using io.js)

**Comment by soulwire** [comment]
Ah yes of course, I saw the es6 syntax so should have thought of that. `svgshelf` is being called via `npm run` so I'll work out how to add the flag there.

Thanks :)
